import type {
  Beat,
  DispatchRecord,
  Order,
  PersistedState,
  Product,
  Profile,
  PurchaseBill,
  Shop,
  StockMovement,
  Transaction,
} from "@/lib/types";

const seedProfile: Profile = {
  name: "Rahul Sharma",
  role: "Senior Sales Executive",
  zone: "North Zone - Beat Sector 4",
  online: true,
  phone: "+91 98200 45678",
  address: "Flat 402, Shanti Residency, Pune 411001",
};

const seedBeats: Beat[] = [
  {
    id: "rambagh",
    name: "Rambagh",
    area: "Central District - Zone A",
    location: "Central District",
    salesToday: 4500,
  },
  {
    id: "city-center",
    name: "City Center",
    area: "Downtown Metro Hub",
    location: "Downtown",
    salesToday: 0,
  },
  {
    id: "commercial-hub",
    name: "Commercial Hub",
    area: "Trade Tower Complex",
    location: "Trade Tower",
    salesToday: 0,
  },
  {
    id: "station-road",
    name: "Station Road",
    area: "East Transit Line",
    location: "East Transit",
    salesToday: 0,
  },
  {
    id: "gandhi-nagar",
    name: "Gandhi Nagar",
    area: "West Residential Belt",
    location: "West Belt",
    salesToday: 0,
  },
  {
    id: "market-yard",
    name: "Market Yard",
    area: "South Wholesale Zone",
    location: "South Zone",
    salesToday: 0,
  },
];

const seedShops: Shop[] = [
  {
    id: "s1",
    beatId: "rambagh",
    name: "Sharma Kirana Store",
    owner: "Ramesh Sharma",
    phone: "+91 98765 12345",
    address: "Shop 14, Main Bazaar, Rambagh",
    dues: 14500,
    status: "pending",
  },
  {
    id: "s2",
    beatId: "rambagh",
    name: "Gupta Provision Hub",
    owner: "Suresh Gupta",
    phone: "+91 98123 45678",
    address: "45 Station Road, Rambagh",
    dues: 8200,
    status: "ordered",
    orderAmount: 4500,
  },
  {
    id: "s3",
    beatId: "rambagh",
    name: "Verma General Store",
    owner: "Anil Varma",
    phone: "+91 99887 76655",
    address: "Mall Road, Rambagh",
    dues: 17000,
    status: "paid",
    paidAmount: 5000,
  },
  {
    id: "s4",
    beatId: "rambagh",
    name: "Royal Traders",
    owner: "Vikram Singh",
    phone: "+91 97654 32109",
    address: "Sector 3 Market, Rambagh",
    dues: 5400,
    status: "pending",
  },
  {
    id: "s5",
    beatId: "city-center",
    name: "Apex Supermarket",
    owner: "Neha Jain",
    phone: "+91 90000 11111",
    address: "MG Road, City Center",
    dues: 22000,
    status: "pending",
  },
  {
    id: "s6",
    beatId: "city-center",
    name: "Metro Cash & Carry",
    owner: "Rohit Mehta",
    phone: "+91 90000 22222",
    address: "Metro Plaza, City Center",
    dues: 18000,
    status: "pending",
  },
  {
    id: "s7",
    beatId: "city-center",
    name: "Star Bazaar",
    owner: "Kavya Rao",
    phone: "+91 90000 33333",
    address: "Ring Road, City Center",
    dues: 14000,
    status: "pending",
  },
  {
    id: "s8",
    beatId: "commercial-hub",
    name: "Prime Wholesale",
    owner: "Amit Shah",
    phone: "+91 90000 44444",
    address: "Tower A, Commercial Hub",
    dues: 30000,
    status: "pending",
  },
  {
    id: "s9",
    beatId: "commercial-hub",
    name: "Unity Distributors",
    owner: "Sana Khan",
    phone: "+91 90000 55555",
    address: "Tower C, Commercial Hub",
    dues: 27000,
    status: "pending",
  },
  {
    id: "s10",
    beatId: "station-road",
    name: "Transit Mart",
    owner: "Deepak Nair",
    phone: "+91 90000 66666",
    address: "Platform Lane, Station Road",
    dues: 9100,
    status: "pending",
  },
  {
    id: "s11",
    beatId: "station-road",
    name: "Junction Stores",
    owner: "Priya Das",
    phone: "+91 90000 77777",
    address: "Exit Gate, Station Road",
    dues: 7000,
    status: "pending",
  },
];

const seedProducts: Product[] = [
  {
    id: "p1",
    name: "Cooking Oil 1L",
    code: "PRD-001",
    buyingPrice: 120,
    sellingPrice: 145,
    unit: "Pcs",
    openingStock: 80,
    lowStockThreshold: 20,
  },
  {
    id: "p2",
    name: "Tea 500g",
    code: "PRD-002",
    buyingPrice: 210,
    sellingPrice: 260,
    unit: "Pack",
    openingStock: 45,
    lowStockThreshold: 15,
  },
  {
    id: "p3",
    name: "Wheat Flour 10kg",
    code: "PRD-003",
    buyingPrice: 340,
    sellingPrice: 399,
    unit: "Pack",
    openingStock: 12,
    lowStockThreshold: 15,
  },
  {
    id: "p4",
    name: "Basmati Rice 5kg",
    code: "PRD-004",
    buyingPrice: 480,
    sellingPrice: 560,
    unit: "Pack",
    openingStock: 25,
    lowStockThreshold: 10,
  },
  {
    id: "p5",
    name: "Sugar 1kg",
    code: "PRD-005",
    buyingPrice: 42,
    sellingPrice: 52,
    unit: "Pcs",
    openingStock: 0,
    lowStockThreshold: 20,
  },
  {
    id: "p6",
    name: "Detergent 1kg",
    code: "PRD-006",
    buyingPrice: 95,
    sellingPrice: 120,
    unit: "Pack",
    openingStock: 60,
    lowStockThreshold: 20,
  },
];

const seedTransactions: Transaction[] = [
  {
    id: "t1",
    type: "order",
    title: "Order: Gupta Provision Hub",
    subtitle: "Rambagh • 10x Cooking Oil 1L, 5x Tea 500g, 2x Flour 10kg",
    amount: 4500,
    time: "10:15 AM",
  },
  {
    id: "t2",
    type: "collection",
    title: "Collection: Apex Supermarket",
    subtitle: "Mode: UPI • Ref: RCP-88902",
    amount: 5000,
    time: "11:30 AM",
  },
];

const seedOrders: Order[] = [
  {
    id: "o-seed-1",
    shopId: "s2",
    shopName: "Gupta Provision Hub",
    beatName: "Rambagh",
    lines: [
      { productId: "p1", qty: 10, price: 145 },
      { productId: "p2", qty: 5, price: 260 },
      { productId: "p3", qty: 2, price: 399 },
    ],
    total: 4500,
    summary: "10x Cooking Oil 1L, 5x Tea 500g, 2x Wheat Flour 10kg",
    status: "pending",
    createdAt: "2026-01-01T04:45:00.000Z",
  },
];

export function buildDefaults(): PersistedState {
  return {
    profile: seedProfile,
    dailyTarget: 60000,
    beats: seedBeats,
    shops: seedShops,
    products: seedProducts,
    transactions: seedTransactions,
    orders: seedOrders,
    purchaseBills: [] as PurchaseBill[],
    stockMovements: [] as StockMovement[],
    dispatches: [] as DispatchRecord[],
    syncEnabled: true,
  };
}
