buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'
        classpath 'com.google.gms:google-services:4.4.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
    minSdkVersion = 23
    compileSdkVersion = 35
    targetSdkVersion = 35
    
    // प्लगइंस द्वारा मांगे जाने वाले सभी वर्जन्स यहाँ डिफाइन कर दिए गए हैं
    androidxAppCompatVersion = '1.6.1'
    androidxCoreKTXVersion = '1.12.0'
    androidxCoordinatorLayoutVersion = '1.2.0'
    androidxJunitVersion = '1.1.5'
    androidxEspressoCoreVersion = '3.5.1'
    junitVersion = '4.13.2'
    coreSplashScreenVersion = '1.0.1'
}